// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Fall back to Scalingo's provider-specific var so `prisma migrate deploy`
    // works on the platform without setting DATABASE_URL manually.
    url:
      process.env["DATABASE_URL"] ||
      process.env["SCALINGO_POSTGRESQL_URL"] ||
      "postgresql://localhost:5432/crawlseo",
  },
});
